# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918323e711f7b0e2dd7bf905f62f1bce29c1cb53b8ec5c978f63f4536239bcaf51d49122b71427f625ada14b34f785231d50755145344a6546152b0945209880

test:
  secret_key_base: 3e1c8ddf86134e24f61bf254f0ad225a13f94e5a183b7934a98ff339c07fd4ad3d553772a425985a30199be62d31e396413b0c419ae5b923cbeefb37d37b6d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
